[package]
name = "renskin"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rskd"
path = "src/main.rs"

[features]
default = []
avx2 = []
nomn = []

[dependencies]
anyhow = "1"
async-fs = "2"
base64 = "0.22"
clap = { version = "4", features = ["derive", "env"] }
dotenvy = "0.15"
femme = "2"
futures-lite = "2"
log = "0.4"
png = "0.18"
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_urlencoded = "0.7"
sqlx = { version = "0.9", default-features = false, features = ["mysql", "runtime-smol", "macros"] }
thiserror = "2"
trillium = "1"
trillium-client = "0.9"
trillium-rustls = "0.11"
trillium-smol = "0.7"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = "symbols"
