[package]
name = "renskin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.4.0"
dotenvy = "0.15.7"
image = { version = "0.24.7", default-features = false, features = ["png"] }
reqwest = { version = "0.11.20", features = ["rustls"] }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.105"
sqlx = { version = "0.7.1", features = ["runtime-tokio", "tls-rustls", "mysql"] }
tokio = { version = "1", features = ["rt", "sync", "macros", "rt-multi-thread"] }


